/**
 * Direction visuelle : Aquarelle de contrôle — chaque mutation donne un feedback immédiat,
 * réversible et calme, comme un carnet de planification qui se met à jour sans bruit.
 */
import { create } from "zustand";
import type { Notification, PlannerProfile, PlannerTask, TeamMember, ThemeName, ViewName } from "@/lib/types";
import { fallbackTeamMembers } from "@/lib/team";

type PlannerState = { activeView: ViewName; theme: ThemeName; profile: PlannerProfile; tasks: PlannerTask[]; teamMembers: TeamMember[]; selectedAgentIds: string[]; notifications: Notification[]; selectedTaskId: string | null; search: string; sidebarOpen: boolean; taskModalOpen: boolean; setView: (view: ViewName) => void; setTheme: (theme: ThemeName) => void; setProfile: (profile: Partial<PlannerProfile>) => void; setSearch: (search: string) => void; setSidebarOpen: (open: boolean) => void; openTaskModal: (taskId?: string | null) => void; closeTaskModal: () => void; setTasks: (tasks: PlannerTask[]) => void; setTeamMembers: (members: TeamMember[]) => void; setSelectedAgentIds: (ids: string[]) => void; toggleAgent: (id: string) => void; selectAllAgents: () => void; clearAgentSelection: () => void; addTask: (task: PlannerTask) => void; updateTask: (id: string, patch: Partial<PlannerTask>) => void; toggleTask: (id: string) => void; toggleStar: (id: string) => void; addNotification: (notification: Notification) => void; markNotificationRead: (id: string) => void };

const initialTasks: PlannerTask[] = [
  { id: "task-1", title: "Finaliser la proposition commerciale", project: "Northstar rebrand", projectColor: "#69D2FF", category: "Commercial", status: "in_progress", priority: "high", assigneeId: "sam", start: "09:00", end: "10:30", estimate: "1h 30", progress: 68, tags: ["Revue", "Client"], date: "2026-08-11", starred: true },
  { id: "task-2", title: "Revue du parcours onboarding", project: "Équipe produit", projectColor: "#B5A1FF", category: "Produit", status: "todo", priority: "medium", assigneeId: "michael", start: "11:00", end: "12:00", estimate: "1h", progress: 24, tags: ["UX", "Prioritaire"], date: "2026-08-11" },
  { id: "task-3", title: "Synchronisation créative", project: "Studio Aurora", projectColor: "#6FE3C1", category: "Réunion", status: "in_progress", priority: "low", assigneeId: "bradley", start: "13:30", end: "14:15", estimate: "45 min", progress: 42, tags: ["Équipe"], date: "2026-08-11" },
  { id: "task-4", title: "Préparer les assets de lancement", project: "Northstar rebrand", projectColor: "#69D2FF", category: "Design", status: "done", priority: "high", assigneeId: "daniel", start: "14:30", end: "16:00", estimate: "1h 30", progress: 100, tags: ["Design", "Livraison"], date: "2026-08-11" },
  { id: "task-5", title: "QA mobile et derniers ajustements", project: "Portail Mon Essentiel", projectColor: "#F0B36D", category: "Développement", status: "blocked", priority: "urgent", assigneeId: "herve", start: "16:30", end: "17:30", estimate: "1h", progress: 56, tags: ["Bloqué", "Mobile"], date: "2026-08-12" },
];

export const usePlannerStore = create<PlannerState>((set) => ({ activeView: "dashboard", theme: "dark", profile: { id: "self", fullName: "Eldo", email: "eldorado.design1@gmail.com", role: "super_admin", locale: "fr", theme: "dark" }, tasks: initialTasks, teamMembers: fallbackTeamMembers, selectedAgentIds: fallbackTeamMembers.map((member) => member.id), notifications: [], selectedTaskId: null, search: "", sidebarOpen: true, taskModalOpen: false, setView: (activeView) => set({ activeView }), setTheme: (theme) => set((state) => ({ theme, profile: { ...state.profile, theme } })), setProfile: (profile) => set((state) => ({ profile: { ...state.profile, ...profile }, theme: profile.theme ?? state.theme })), setSearch: (search) => set({ search }), setSidebarOpen: (sidebarOpen) => set({ sidebarOpen }), openTaskModal: (selectedTaskId = null) => set({ selectedTaskId, taskModalOpen: true }), closeTaskModal: () => set({ selectedTaskId: null, taskModalOpen: false }), setTasks: (tasks) => set({ tasks }), setTeamMembers: (teamMembers) => set((state) => { const retained = state.selectedAgentIds.filter((id) => teamMembers.some((member) => member.id === id)); return { teamMembers, selectedAgentIds: retained.length ? retained : teamMembers.map((member) => member.id) }; }), setSelectedAgentIds: (selectedAgentIds) => set({ selectedAgentIds }), toggleAgent: (id) => set((state) => ({ selectedAgentIds: state.selectedAgentIds.includes(id) ? state.selectedAgentIds.filter((agentId) => agentId !== id) : [...state.selectedAgentIds, id] })), selectAllAgents: () => set((state) => ({ selectedAgentIds: state.teamMembers.map((member) => member.id) })), clearAgentSelection: () => set({ selectedAgentIds: [] }), addTask: (task) => set((state) => ({ tasks: [task, ...state.tasks], taskModalOpen: false })), updateTask: (id, patch) => set((state) => ({ tasks: state.tasks.map((task) => task.id === id ? { ...task, ...patch } : task), taskModalOpen: false })), toggleTask: (id) => set((state) => ({ tasks: state.tasks.map((task) => task.id === id ? { ...task, status: task.status === "done" ? "in_progress" : "done", progress: task.status === "done" ? 68 : 100 } : task) })), toggleStar: (id) => set((state) => ({ tasks: state.tasks.map((task) => task.id === id ? { ...task, starred: !task.starred } : task) })), addNotification: (notification) => set((state) => ({ notifications: [notification, ...state.notifications.filter((item) => item.id !== notification.id)] })), markNotificationRead: (id) => set((state) => ({ notifications: state.notifications.map((item) => item.id === id ? { ...item, unread: false } : item) })) }));
